name: WildPlugin
main: gxplugins.wild.Wild
version: "1.0"
api: ["1.0.5"]
author: PikyCZ

commands:
  wild:
    description: You've been teleported somewhere wild
    aliases: ["wild"]
    usage: "/wild"
    permission: gxwild.command.wild
    
permissions:
  gxwild.command.wild:
    description: ""
    default: true
