name: WildPlugin
description: "A tiny plugin that adds a very primitive random teleport command."
authors: ["PikyCZ", "Incomp"]
main: gxplugins.wild.Wild
api: ["1.0.5"]
version: ${project.version}


commands:
  wild:
    description: "Used to teleport to a random place."
    aliases: ["/randomtp", "/rtp", "/wilderness"]
    usage: "/wild"
    permission: gxwild.command.wild
    
permissions:
  gxwild.command.wild:
    default: true
